/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManagmentSystem;

import connectionProvider.connectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author 91887
 */
public class studentDetails extends javax.swing.JFrame {

    /**
     * Creates new form studentDetails
     */
    public studentDetails() {
        initComponents();
    }
    public studentDetails(String rollno) {
        initComponents();
        rollnofield.setText(rollno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        genderfield = new javax.swing.JTextField();
        coursefield = new javax.swing.JTextField();
        rollnofield = new javax.swing.JTextField();
        parentnamefield = new javax.swing.JTextField();
        branchfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        physicfield = new javax.swing.JTextField();
        mathfield = new javax.swing.JTextField();
        chemestryfield = new javax.swing.JTextField();
        electricalfield = new javax.swing.JTextField();
        biofield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(860, 680));
        setMinimumSize(new java.awt.Dimension(860, 680));
        setPreferredSize(new java.awt.Dimension(860, 680));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 55, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Gender");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 101, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Course");
        jLabel3.setMaximumSize(new java.awt.Dimension(70, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(70, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 154, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("RollNo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 55, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Parent Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 108, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Branch");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 161, -1, -1));

        namefield.setMaximumSize(new java.awt.Dimension(120, 30));
        namefield.setMinimumSize(new java.awt.Dimension(120, 30));
        namefield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 48, -1, -1));

        genderfield.setMaximumSize(new java.awt.Dimension(120, 30));
        genderfield.setMinimumSize(new java.awt.Dimension(120, 30));
        genderfield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 101, -1, -1));

        coursefield.setMaximumSize(new java.awt.Dimension(120, 30));
        coursefield.setMinimumSize(new java.awt.Dimension(120, 30));
        coursefield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(coursefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 154, -1, -1));

        rollnofield.setMaximumSize(new java.awt.Dimension(120, 30));
        rollnofield.setMinimumSize(new java.awt.Dimension(120, 30));
        rollnofield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(rollnofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 48, -1, -1));

        parentnamefield.setMaximumSize(new java.awt.Dimension(120, 30));
        parentnamefield.setMinimumSize(new java.awt.Dimension(120, 30));
        parentnamefield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(parentnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 101, -1, -1));

        branchfield.setMaximumSize(new java.awt.Dimension(120, 30));
        branchfield.setMinimumSize(new java.awt.Dimension(120, 30));
        branchfield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(branchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 154, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Physics");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 278, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("MathMatics");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Chemestry");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Electrical");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 445, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Bio");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 507, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Total Marks");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 234, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Passing Marks");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 234, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Marks Obtained");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 234, -1, -1));

        physicfield.setMaximumSize(new java.awt.Dimension(120, 30));
        physicfield.setMinimumSize(new java.awt.Dimension(120, 30));
        physicfield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(physicfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 271, -1, -1));

        mathfield.setMaximumSize(new java.awt.Dimension(120, 30));
        mathfield.setMinimumSize(new java.awt.Dimension(120, 30));
        mathfield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(mathfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 327, -1, -1));

        chemestryfield.setMaximumSize(new java.awt.Dimension(120, 30));
        chemestryfield.setMinimumSize(new java.awt.Dimension(120, 30));
        chemestryfield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(chemestryfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 378, -1, -1));

        electricalfield.setMaximumSize(new java.awt.Dimension(120, 30));
        electricalfield.setMinimumSize(new java.awt.Dimension(120, 30));
        electricalfield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(electricalfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 438, -1, -1));

        biofield.setMaximumSize(new java.awt.Dimension(120, 30));
        biofield.setMinimumSize(new java.awt.Dimension(120, 30));
        biofield.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(biofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("100");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 278, 43, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("100");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 334, 43, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("100");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 392, 43, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("100");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 445, 43, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("100");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 507, 43, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("30");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 278, 43, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("30");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 334, 43, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("30");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 392, 43, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("30");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 445, 43, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("30");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 507, 43, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Result");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Verdict");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, -1));

        jTextField1.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField1.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jTextField2.setMaximumSize(new java.awt.Dimension(80, 30));
        jTextField2.setMinimumSize(new java.awt.Dimension(80, 30));
        jTextField2.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagmentSystem/schoolPic2.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String RollNo=rollnofield.getText();
        try{
            Connection con=connectionProvider.getcon();
            Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        ResultSet rs=st.executeQuery("SELECT * FROM student INNER JOIN result WHERE student.roolno='"+RollNo+"' AND result.roolno='"+RollNo+"';");
       if(!rs.first()){
           JOptionPane.showMessageDialog(null, "Result Not Found");
       }
       else{
        namefield.setText(rs.getString(1));
        branchfield.setText(rs.getString(6));
        coursefield.setText(rs.getString(5));
        parentnamefield.setText(rs.getString(4));
        genderfield.setText(rs.getString(3));
        physicfield.setText(rs.getString(8));
        chemestryfield.setText(rs.getString(9));
        mathfield.setText(rs.getString(10));
        electricalfield.setText(rs.getString(11));
        biofield.setText(rs.getString(12));
        int physicm=Integer.parseInt(physicfield.getText());
        int chemestrym=Integer.parseInt(chemestryfield.getText());
        int mathm=Integer.parseInt(mathfield.getText());
        int elecm=Integer.parseInt(electricalfield.getText());
        int biom=Integer.parseInt(biofield.getText());
        if(physicm<30||chemestrym<30||mathm<30||elecm<30||biom<30){
            jTextField2.setText("Fail");
        }
        else{
            jTextField2.setText("Pass");
        }
        jTextField1.setText(rs.getString(13));
        }
       namefield.setEditable(false);
      genderfield.setEditable(false);
       branchfield.setEditable(false);
       coursefield.setEditable(false);
      parentnamefield.setEditable(false);
       physicfield.setEditable(false);
    chemestryfield.setEditable(false);
       mathfield.setEditable(false);
       electricalfield.setEditable(false);
       biofield.setEditable(false);
       jTextField1.setEditable(false);
       jTextField2.setEditable(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        StudentHomePage frame=new StudentHomePage();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biofield;
    private javax.swing.JTextField branchfield;
    private javax.swing.JTextField chemestryfield;
    private javax.swing.JTextField coursefield;
    private javax.swing.JTextField electricalfield;
    private javax.swing.JTextField genderfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField mathfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField parentnamefield;
    private javax.swing.JTextField physicfield;
    private javax.swing.JTextField rollnofield;
    // End of variables declaration//GEN-END:variables
}
